version: '2'
jobs:
  integration-test:
    machine:
      image: circleci/classic:201711-01
    working_directory: ~/code
    steps:
      - checkout
      - run:
          name: Install dependencies
          working_directory: ~/code
          command: |
            sudo apt update && sudo apt install -yq python3-pip
            pip install -r integration-test/test_requirements.txt
      - run:
          name: Run basic tests
          working_directory: ~/code
          command: bash verify.sh
      - run:
          name: Run integration tests
          working_directory: ~/code
          command: pytest -n4 integration_tests
  unittest:
    docker:
      - image: python:2.7-stretch
    working_directory: ~/code
    steps:
      - checkout
      - run:
          name: Install test dependencies
          command: |
            pip install -r test/test_requirements.txt
      - run:
          name: Execute Tests
          command: |
            bash verify.sh

workflows:
  version: 2
  build:
    jobs:
      - unittest
      - integration-test
